export const TESTIMONIALS = [
  {
    name: 'Rajesh Kumar',
    designation: 'Managing Director',
    company: 'Kumar Enterprises Pvt. Ltd.',
    content: 'Delhi Filing handled our company incorporation and annual compliance seamlessly. Their team is highly professional and responsive. We got our Private Limited Company registered in just 12 days.',
    rating: 5,
    order: 1,
  },
  {
    name: 'Advocate Priya Sharma',
    designation: 'Senior Advocate',
    company: 'Delhi High Court',
    content: 'I have been using Delhi Filing for eCourt filing services for over 2 years. Their turnaround time is excellent and they understand the urgency of legal deadlines. Highly recommended for advocates.',
    rating: 5,
    order: 2,
  },
  {
    name: 'Suresh Agarwal',
    designation: 'Proprietor',
    company: 'Agarwal Construction',
    content: 'We won a major government tender with Delhi Filing\'s support. Their technical bid preparation and GeM registration services are top-notch. Very knowledgeable team.',
    rating: 5,
    order: 3,
  },
  {
    name: 'Meena Joshi',
    designation: 'Director',
    company: 'Joshi Foods Pvt. Ltd.',
    content: 'Got our FSSAI licence, GST registration and company incorporation all done through Delhi Filing. One-stop solution for all compliance needs. Saved us a lot of time and hassle.',
    rating: 5,
    order: 4,
  },
  {
    name: 'Amit Verma',
    designation: 'Partner',
    company: 'Verma & Associates LLP',
    content: 'Delhi Filing helped us convert our partnership firm to LLP smoothly. The process was explained clearly and completed on time. Their compliance calendar service is very useful.',
    rating: 5,
    order: 5,
  },
  {
    name: 'Sunita Kapoor',
    designation: 'Individual Client',
    company: '',
    content: 'Filed my divorce petition and maintenance case through Delhi Filing. They were very professional and sensitive in handling the matter. Got the filing done quickly and correctly.',
    rating: 5,
    order: 6,
  },
]
